/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class BioAPI_BIR {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BioAPI_BIR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BioAPI_BIR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      BioAPIJNI.delete_BioAPI_BIR(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setHeader(BioAPI_BIR_HEADER Header) {
    BioAPIJNI.set_BioAPI_BIR_Header(swigCPtr, BioAPI_BIR_HEADER.getCPtr(Header));
  }

  public BioAPI_BIR_HEADER getHeader() {
    long cPtr = BioAPIJNI.get_BioAPI_BIR_Header(swigCPtr);
    return (cPtr == 0) ? null : new BioAPI_BIR_HEADER(cPtr, false);
  }

  public void setBiometricData(SWIGTYPE_p_unsigned_char BiometricData) {
    BioAPIJNI.set_BioAPI_BIR_BiometricData(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(BiometricData));
  }

  public SWIGTYPE_p_unsigned_char getBiometricData() {
    long cPtr = BioAPIJNI.get_BioAPI_BIR_BiometricData(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setSignature(BioAPI_DATA Signature) {
    BioAPIJNI.set_BioAPI_BIR_Signature(swigCPtr, BioAPI_DATA.getCPtr(Signature));
  }

  public BioAPI_DATA getSignature() {
    long cPtr = BioAPIJNI.get_BioAPI_BIR_Signature(swigCPtr);
    return (cPtr == 0) ? null : new BioAPI_DATA(cPtr, false);
  }

  public BioAPI_BIR() {
    this(BioAPIJNI.new_BioAPI_BIR(), true);
  }

}
