/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class BioAPI_GUI_BITMAP {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BioAPI_GUI_BITMAP(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BioAPI_GUI_BITMAP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      BioAPIJNI.delete_BioAPI_GUI_BITMAP(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setWidth(long Width) {
    BioAPIJNI.set_BioAPI_GUI_BITMAP_Width(swigCPtr, Width);
  }

  public long getWidth() {
    return BioAPIJNI.get_BioAPI_GUI_BITMAP_Width(swigCPtr);
  }

  public void setHeight(long Height) {
    BioAPIJNI.set_BioAPI_GUI_BITMAP_Height(swigCPtr, Height);
  }

  public long getHeight() {
    return BioAPIJNI.get_BioAPI_GUI_BITMAP_Height(swigCPtr);
  }

  public void setBitmap(BioAPI_DATA Bitmap) {
    BioAPIJNI.set_BioAPI_GUI_BITMAP_Bitmap(swigCPtr, BioAPI_DATA.getCPtr(Bitmap));
  }

  public BioAPI_DATA getBitmap() {
    long cPtr = BioAPIJNI.get_BioAPI_GUI_BITMAP_Bitmap(swigCPtr);
    return (cPtr == 0) ? null : new BioAPI_DATA(cPtr, false);
  }

  public BioAPI_GUI_BITMAP() {
    this(BioAPIJNI.new_BioAPI_GUI_BITMAP(), true);
  }

}
