/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class BioAPI_INPUT_BIR_InputBIR {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BioAPI_INPUT_BIR_InputBIR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BioAPI_INPUT_BIR_InputBIR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      BioAPIJNI.delete_BioAPI_INPUT_BIR_InputBIR(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setBIRinDb(BioAPI_DBBIR_ID BIRinDb) {
    BioAPIJNI.set_BioAPI_INPUT_BIR_InputBIR_BIRinDb(swigCPtr, BioAPI_DBBIR_ID.getCPtr(BIRinDb));
  }

  public BioAPI_DBBIR_ID getBIRinDb() {
    long cPtr = BioAPIJNI.get_BioAPI_INPUT_BIR_InputBIR_BIRinDb(swigCPtr);
    return (cPtr == 0) ? null : new BioAPI_DBBIR_ID(cPtr, false);
  }

  public void setBIRinBSP(SWIGTYPE_p_int BIRinBSP) {
    BioAPIJNI.set_BioAPI_INPUT_BIR_InputBIR_BIRinBSP(swigCPtr, SWIGTYPE_p_int.getCPtr(BIRinBSP));
  }

  public SWIGTYPE_p_int getBIRinBSP() {
    long cPtr = BioAPIJNI.get_BioAPI_INPUT_BIR_InputBIR_BIRinBSP(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setBIR(BioAPI_BIR BIR) {
    BioAPIJNI.set_BioAPI_INPUT_BIR_InputBIR_BIR(swigCPtr, BioAPI_BIR.getCPtr(BIR));
  }

  public BioAPI_BIR getBIR() {
    long cPtr = BioAPIJNI.get_BioAPI_INPUT_BIR_InputBIR_BIR(swigCPtr);
    return (cPtr == 0) ? null : new BioAPI_BIR(cPtr, false);
  }

  public BioAPI_INPUT_BIR_InputBIR() {
    this(BioAPIJNI.new_BioAPI_INPUT_BIR_InputBIR(), true);
  }

}
