/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class BioAPI_BIR_HEADER {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BioAPI_BIR_HEADER(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BioAPI_BIR_HEADER obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      BioAPIJNI.delete_BioAPI_BIR_HEADER(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setLength(long Length) {
    BioAPIJNI.set_BioAPI_BIR_HEADER_Length(swigCPtr, Length);
  }

  public long getLength() {
    return BioAPIJNI.get_BioAPI_BIR_HEADER_Length(swigCPtr);
  }

  public void setHeaderVersion(short HeaderVersion) {
    BioAPIJNI.set_BioAPI_BIR_HEADER_HeaderVersion(swigCPtr, HeaderVersion);
  }

  public short getHeaderVersion() {
    return BioAPIJNI.get_BioAPI_BIR_HEADER_HeaderVersion(swigCPtr);
  }

  public void setType(short Type) {
    BioAPIJNI.set_BioAPI_BIR_HEADER_Type(swigCPtr, Type);
  }

  public short getType() {
    return BioAPIJNI.get_BioAPI_BIR_HEADER_Type(swigCPtr);
  }

  public void setFormat(BioAPI_BIR_BIOMETRIC_DATA_FORMAT Format) {
    BioAPIJNI.set_BioAPI_BIR_HEADER_Format(swigCPtr, BioAPI_BIR_BIOMETRIC_DATA_FORMAT.getCPtr(Format));
  }

  public BioAPI_BIR_BIOMETRIC_DATA_FORMAT getFormat() {
    long cPtr = BioAPIJNI.get_BioAPI_BIR_HEADER_Format(swigCPtr);
    return (cPtr == 0) ? null : new BioAPI_BIR_BIOMETRIC_DATA_FORMAT(cPtr, false);
  }

  public void setQuality(char Quality) {
    BioAPIJNI.set_BioAPI_BIR_HEADER_Quality(swigCPtr, Quality);
  }

  public char getQuality() {
    return BioAPIJNI.get_BioAPI_BIR_HEADER_Quality(swigCPtr);
  }

  public void setPurpose(short Purpose) {
    BioAPIJNI.set_BioAPI_BIR_HEADER_Purpose(swigCPtr, Purpose);
  }

  public short getPurpose() {
    return BioAPIJNI.get_BioAPI_BIR_HEADER_Purpose(swigCPtr);
  }

  public void setFactorsMask(long FactorsMask) {
    BioAPIJNI.set_BioAPI_BIR_HEADER_FactorsMask(swigCPtr, FactorsMask);
  }

  public long getFactorsMask() {
    return BioAPIJNI.get_BioAPI_BIR_HEADER_FactorsMask(swigCPtr);
  }

  public BioAPI_BIR_HEADER() {
    this(BioAPIJNI.new_BioAPI_BIR_HEADER(), true);
  }

}
