/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class BioAPI_IDENTIFY_POPULATION {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BioAPI_IDENTIFY_POPULATION(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BioAPI_IDENTIFY_POPULATION obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      BioAPIJNI.delete_BioAPI_IDENTIFY_POPULATION(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setType(short Type) {
    BioAPIJNI.set_BioAPI_IDENTIFY_POPULATION_Type(swigCPtr, Type);
  }

  public short getType() {
    return BioAPIJNI.get_BioAPI_IDENTIFY_POPULATION_Type(swigCPtr);
  }

  public BioAPI_IDENTIFY_POPULATION_BIRs getBIRs() {
    long cPtr = BioAPIJNI.get_BioAPI_IDENTIFY_POPULATION_BIRs(swigCPtr);
    return (cPtr == 0) ? null : new BioAPI_IDENTIFY_POPULATION_BIRs(cPtr, false);
  }

  public BioAPI_IDENTIFY_POPULATION() {
    this(BioAPIJNI.new_BioAPI_IDENTIFY_POPULATION(), true);
  }

}
