/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class BioAPI_INPUT_BIR {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BioAPI_INPUT_BIR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BioAPI_INPUT_BIR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      BioAPIJNI.delete_BioAPI_INPUT_BIR(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setForm(short Form) {
    BioAPIJNI.set_BioAPI_INPUT_BIR_Form(swigCPtr, Form);
  }

  public short getForm() {
    return BioAPIJNI.get_BioAPI_INPUT_BIR_Form(swigCPtr);
  }

  public BioAPI_INPUT_BIR_InputBIR getInputBIR() {
    long cPtr = BioAPIJNI.get_BioAPI_INPUT_BIR_InputBIR(swigCPtr);
    return (cPtr == 0) ? null : new BioAPI_INPUT_BIR_InputBIR(cPtr, false);
  }

  public BioAPI_INPUT_BIR() {
    this(BioAPIJNI.new_BioAPI_INPUT_BIR(), true);
  }

}
