/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class BioAPI_FUNC_NAME_ADDR {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BioAPI_FUNC_NAME_ADDR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BioAPI_FUNC_NAME_ADDR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      BioAPIJNI.delete_BioAPI_FUNC_NAME_ADDR(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setName(String Name) {
    BioAPIJNI.set_BioAPI_FUNC_NAME_ADDR_Name(swigCPtr, Name);
  }

  public String getName() {
    return BioAPIJNI.get_BioAPI_FUNC_NAME_ADDR_Name(swigCPtr);
  }

  public void setAddress(SWIGTYPE_p_f___void Address) {
    BioAPIJNI.set_BioAPI_FUNC_NAME_ADDR_Address(swigCPtr, SWIGTYPE_p_f___void.getCPtr(Address));
  }

  public SWIGTYPE_p_f___void getAddress() {
    long cPtr = BioAPIJNI.get_BioAPI_FUNC_NAME_ADDR_Address(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f___void(cPtr, false);
  }

  public BioAPI_FUNC_NAME_ADDR() {
    this(BioAPIJNI.new_BioAPI_FUNC_NAME_ADDR(), true);
  }

}
