/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class BioAPI_BSP_SCHEMA {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BioAPI_BSP_SCHEMA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BioAPI_BSP_SCHEMA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      BioAPIJNI.delete_BioAPI_BSP_SCHEMA(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setModuleId(SWIGTYPE_p_unsigned_char ModuleId) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_ModuleId(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(ModuleId));
  }

  public SWIGTYPE_p_unsigned_char getModuleId() {
    long cPtr = BioAPIJNI.get_BioAPI_BSP_SCHEMA_ModuleId(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setDeviceId(long DeviceId) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_DeviceId(swigCPtr, DeviceId);
  }

  public long getDeviceId() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_DeviceId(swigCPtr);
  }

  public void setBSPName(String BSPName) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_BSPName(swigCPtr, BSPName);
  }

  public String getBSPName() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_BSPName(swigCPtr);
  }

  public void setSpecVersion(BioAPI_VERSION SpecVersion) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_SpecVersion(swigCPtr, BioAPI_VERSION.getCPtr(SpecVersion));
  }

  public BioAPI_VERSION getSpecVersion() {
    long cPtr = BioAPIJNI.get_BioAPI_BSP_SCHEMA_SpecVersion(swigCPtr);
    return (cPtr == 0) ? null : new BioAPI_VERSION(cPtr, false);
  }

  public void setProductVersion(BioAPI_VERSION ProductVersion) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_ProductVersion(swigCPtr, BioAPI_VERSION.getCPtr(ProductVersion));
  }

  public BioAPI_VERSION getProductVersion() {
    long cPtr = BioAPIJNI.get_BioAPI_BSP_SCHEMA_ProductVersion(swigCPtr);
    return (cPtr == 0) ? null : new BioAPI_VERSION(cPtr, false);
  }

  public void setVendor(String Vendor) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_Vendor(swigCPtr, Vendor);
  }

  public String getVendor() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_Vendor(swigCPtr);
  }

  public void setBspSupportedFormats(BioAPI_BIR_BIOMETRIC_DATA_FORMAT BspSupportedFormats) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_BspSupportedFormats(swigCPtr, BioAPI_BIR_BIOMETRIC_DATA_FORMAT.getCPtr(BspSupportedFormats));
  }

  public BioAPI_BIR_BIOMETRIC_DATA_FORMAT getBspSupportedFormats() {
    long cPtr = BioAPIJNI.get_BioAPI_BSP_SCHEMA_BspSupportedFormats(swigCPtr);
    return (cPtr == 0) ? null : new BioAPI_BIR_BIOMETRIC_DATA_FORMAT(cPtr, false);
  }

  public void setNumSupportedFormats(long NumSupportedFormats) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_NumSupportedFormats(swigCPtr, NumSupportedFormats);
  }

  public long getNumSupportedFormats() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_NumSupportedFormats(swigCPtr);
  }

  public void setFactorsMask(long FactorsMask) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_FactorsMask(swigCPtr, FactorsMask);
  }

  public long getFactorsMask() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_FactorsMask(swigCPtr);
  }

  public void setOperations(long Operations) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_Operations(swigCPtr, Operations);
  }

  public long getOperations() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_Operations(swigCPtr);
  }

  public void setOptions(long Options) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_Options(swigCPtr, Options);
  }

  public long getOptions() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_Options(swigCPtr);
  }

  public void setPayloadPolicy(long PayloadPolicy) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_PayloadPolicy(swigCPtr, PayloadPolicy);
  }

  public long getPayloadPolicy() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_PayloadPolicy(swigCPtr);
  }

  public void setMaxPayloadSize(long MaxPayloadSize) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_MaxPayloadSize(swigCPtr, MaxPayloadSize);
  }

  public long getMaxPayloadSize() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_MaxPayloadSize(swigCPtr);
  }

  public void setDefaultVerifyTimeout(int DefaultVerifyTimeout) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_DefaultVerifyTimeout(swigCPtr, DefaultVerifyTimeout);
  }

  public int getDefaultVerifyTimeout() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_DefaultVerifyTimeout(swigCPtr);
  }

  public void setDefaultIdentifyTimeout(int DefaultIdentifyTimeout) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_DefaultIdentifyTimeout(swigCPtr, DefaultIdentifyTimeout);
  }

  public int getDefaultIdentifyTimeout() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_DefaultIdentifyTimeout(swigCPtr);
  }

  public void setDefaultCaptureTimeout(int DefaultCaptureTimeout) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_DefaultCaptureTimeout(swigCPtr, DefaultCaptureTimeout);
  }

  public int getDefaultCaptureTimeout() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_DefaultCaptureTimeout(swigCPtr);
  }

  public void setDefaultEnrollTimeout(int DefaultEnrollTimeout) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_DefaultEnrollTimeout(swigCPtr, DefaultEnrollTimeout);
  }

  public int getDefaultEnrollTimeout() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_DefaultEnrollTimeout(swigCPtr);
  }

  public void setMaxBspDbSize(long MaxBspDbSize) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_MaxBspDbSize(swigCPtr, MaxBspDbSize);
  }

  public long getMaxBspDbSize() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_MaxBspDbSize(swigCPtr);
  }

  public void setMaxIdentify(long MaxIdentify) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_MaxIdentify(swigCPtr, MaxIdentify);
  }

  public long getMaxIdentify() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_MaxIdentify(swigCPtr);
  }

  public void setDescription(String Description) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_Description(swigCPtr, Description);
  }

  public String getDescription() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_Description(swigCPtr);
  }

  public void setPath(char Path) {
    BioAPIJNI.set_BioAPI_BSP_SCHEMA_Path(swigCPtr, Path);
  }

  public char getPath() {
    return BioAPIJNI.get_BioAPI_BSP_SCHEMA_Path(swigCPtr);
  }

  public BioAPI_BSP_SCHEMA() {
    this(BioAPIJNI.new_BioAPI_BSP_SCHEMA(), true);
  }

}
