/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class BioAPI_IDENTIFY_POPULATION_BIRs {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BioAPI_IDENTIFY_POPULATION_BIRs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BioAPI_IDENTIFY_POPULATION_BIRs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      BioAPIJNI.delete_BioAPI_IDENTIFY_POPULATION_BIRs(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setBIRDataBase(SWIGTYPE_p_int BIRDataBase) {
    BioAPIJNI.set_BioAPI_IDENTIFY_POPULATION_BIRs_BIRDataBase(swigCPtr, SWIGTYPE_p_int.getCPtr(BIRDataBase));
  }

  public SWIGTYPE_p_int getBIRDataBase() {
    long cPtr = BioAPIJNI.get_BioAPI_IDENTIFY_POPULATION_BIRs_BIRDataBase(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setBIRArray(BioAPI_BIR_ARRAY_POPULATION BIRArray) {
    BioAPIJNI.set_BioAPI_IDENTIFY_POPULATION_BIRs_BIRArray(swigCPtr, BioAPI_BIR_ARRAY_POPULATION.getCPtr(BIRArray));
  }

  public BioAPI_BIR_ARRAY_POPULATION getBIRArray() {
    long cPtr = BioAPIJNI.get_BioAPI_IDENTIFY_POPULATION_BIRs_BIRArray(swigCPtr);
    return (cPtr == 0) ? null : new BioAPI_BIR_ARRAY_POPULATION(cPtr, false);
  }

  public BioAPI_IDENTIFY_POPULATION_BIRs() {
    this(BioAPIJNI.new_BioAPI_IDENTIFY_POPULATION_BIRs(), true);
  }

}
