/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class BioAPI_VERSION {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BioAPI_VERSION(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BioAPI_VERSION obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      BioAPIJNI.delete_BioAPI_VERSION(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setMajor(long Major) {
    BioAPIJNI.set_BioAPI_VERSION_Major(swigCPtr, Major);
  }

  public long getMajor() {
    return BioAPIJNI.get_BioAPI_VERSION_Major(swigCPtr);
  }

  public void setMinor(long Minor) {
    BioAPIJNI.set_BioAPI_VERSION_Minor(swigCPtr, Minor);
  }

  public long getMinor() {
    return BioAPIJNI.get_BioAPI_VERSION_Minor(swigCPtr);
  }

  public BioAPI_VERSION() {
    this(BioAPIJNI.new_BioAPI_VERSION(), true);
  }

}
