/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class BioAPI_DBBIR_ID {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BioAPI_DBBIR_ID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BioAPI_DBBIR_ID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      BioAPIJNI.delete_BioAPI_DBBIR_ID(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setDbHandle(int DbHandle) {
    BioAPIJNI.set_BioAPI_DBBIR_ID_DbHandle(swigCPtr, DbHandle);
  }

  public int getDbHandle() {
    return BioAPIJNI.get_BioAPI_DBBIR_ID_DbHandle(swigCPtr);
  }

  public void setKeyValue(SWIGTYPE_p_unsigned_char KeyValue) {
    BioAPIJNI.set_BioAPI_DBBIR_ID_KeyValue(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(KeyValue));
  }

  public SWIGTYPE_p_unsigned_char getKeyValue() {
    long cPtr = BioAPIJNI.get_BioAPI_DBBIR_ID_KeyValue(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BioAPI_DBBIR_ID() {
    this(BioAPIJNI.new_BioAPI_DBBIR_ID(), true);
  }

}
