/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class BioAPI_DATA {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BioAPI_DATA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BioAPI_DATA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      BioAPIJNI.delete_BioAPI_DATA(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setLength(long Length) {
    BioAPIJNI.set_BioAPI_DATA_Length(swigCPtr, Length);
  }

  public long getLength() {
    return BioAPIJNI.get_BioAPI_DATA_Length(swigCPtr);
  }

  public void setData(SWIGTYPE_p_unsigned_char Data) {
    BioAPIJNI.set_BioAPI_DATA_Data(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(Data));
  }

  public SWIGTYPE_p_unsigned_char getData() {
    long cPtr = BioAPIJNI.get_BioAPI_DATA_Data(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public BioAPI_DATA() {
    this(BioAPIJNI.new_BioAPI_DATA(), true);
  }

}
