/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class BioAPI_CANDIDATE {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BioAPI_CANDIDATE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BioAPI_CANDIDATE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      BioAPIJNI.delete_BioAPI_CANDIDATE(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setType(short Type) {
    BioAPIJNI.set_BioAPI_CANDIDATE_Type(swigCPtr, Type);
  }

  public short getType() {
    return BioAPIJNI.get_BioAPI_CANDIDATE_Type(swigCPtr);
  }

  public void setFARAchieved(int FARAchieved) {
    BioAPIJNI.set_BioAPI_CANDIDATE_FARAchieved(swigCPtr, FARAchieved);
  }

  public int getFARAchieved() {
    return BioAPIJNI.get_BioAPI_CANDIDATE_FARAchieved(swigCPtr);
  }

  public void setFRRAchieved(int FRRAchieved) {
    BioAPIJNI.set_BioAPI_CANDIDATE_FRRAchieved(swigCPtr, FRRAchieved);
  }

  public int getFRRAchieved() {
    return BioAPIJNI.get_BioAPI_CANDIDATE_FRRAchieved(swigCPtr);
  }

  public BioAPI_CANDIDATE_BIR getBIR() {
    long cPtr = BioAPIJNI.get_BioAPI_CANDIDATE_BIR(swigCPtr);
    return (cPtr == 0) ? null : new BioAPI_CANDIDATE_BIR(cPtr, false);
  }

  public BioAPI_CANDIDATE() {
    this(BioAPIJNI.new_BioAPI_CANDIDATE(), true);
  }

}
