/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.qrivy.bioapi;

public class SWIGTYPE_p_f_p_q_const__a_16__unsigned_char_p_void_unsigned_int_unsigned_int_unsigned_int__unsigned_int {
  private long swigCPtr;

  protected SWIGTYPE_p_f_p_q_const__a_16__unsigned_char_p_void_unsigned_int_unsigned_int_unsigned_int__unsigned_int(long cPtr, boolean bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_q_const__a_16__unsigned_char_p_void_unsigned_int_unsigned_int_unsigned_int__unsigned_int() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_q_const__a_16__unsigned_char_p_void_unsigned_int_unsigned_int_unsigned_int__unsigned_int obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

